version: 2.4

jobs:
  build:
    docker:
      - image: node:18.13.0
    working_directory: ~/MY-BRAND/learn-express
    steps:
      - checkout:
          path: ~/MY-BRAND
      - run:
          name: Install dependencies
          command: npm install
          
   - run:
          name: Install jest
          command: npm install --save-dev jest
         
   - run:
          name: Install jest
          command:  npm i supertest       
      - run:
          command: npm test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
            
     
 
