version: 2.4

jobs:
  build:
    docker:
      - image: node:18.13.0
    working_directory: ~/MY-BRAND/learn-express
    steps:
      - checkout:
          path: ~/MY-BRAND
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test --coverage 
